apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  name: storagesystem-sample
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: storagecluster-sample
  namespace: odf-operator-system
