name: docker-build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.15"]
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: copy odf-operator repo in go src
      run: |
        mkdir -p /home/runner/go/src/github.com/iamniting
        cp -r /home/runner/work/odf-operator/odf-operator /home/runner/go/src/github.com/iamniting

    - name: run tests and build docker image
      working-directory: "/home/runner/go/src/github.com/iamniting/odf-operator"
      env:
        GOPATH: /home/runner/go
      run: |
        export PATH=$PATH:$GOPATH/bin
        make docker-build
